<?php
$z[0]=Array("global","",136,161);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",309,334);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",377,402);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",450,475);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",522,547);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",598,623);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",675,700);
$z[6][4]['name']="cfg_cmsurl";

?>